--- Sentencias SQL para la creación del esquema de HotelAndes
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- USO
-- Copie el contenido de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada

-- DROP tables

SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

-- Creación del secuenciador
create sequence hotelandes_sequence;

-- Creaación de la tabla HOTEL y especificación de sus restricciones
CREATE TABLE A_HOTEL
   (ID NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
    "DESCRIPTION" VARCHAR2(500 BYTE),
    STARS NUMBER,
    CITY VARCHAR2(255 BYTE),
    ADDRESS VARCHAR2(255 BYTE),
    CURRENCY VARCHAR2(255 BYTE),
	CONSTRAINT A_HOTEL_PK PRIMARY KEY (ID));
	
-- Creaación de la tabla ROOMTYPE y especificación de sus restricciones
CREATE TABLE A_ROOMTYPE
   (ID NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
    "DESCRIPTION" VARCHAR2(500 BYTE),
    "CAPACITY" NUMBER, 
	PRICE NUMBER, 
	CONSTRAINT A_ROOMTYPE_PK PRIMARY KEY (ID));

-- Creaación de la tabla AMENITY y especificación de sus restricciones	
CREATE TABLE A_AMENITY
   (ANAME VARCHAR2(255 BYTE), 
    "DESCRIPTION" VARCHAR2(500 BYTE),
	CONSTRAINT A_AMENITY_PK PRIMARY KEY (ANAME));
    
-- Creaación de la tabla OFFERS y especificación de sus restricciones
CREATE TABLE A_OFFERS
   (ANAMEAMENITY VARCHAR2(255 BYTE), 
	IDROOMTYPE NUMBER,
	CONSTRAINT A_OFFERS_PK PRIMARY KEY (ANAMEAMENITY, IDROOMTYPE));

ALTER TABLE A_OFFERS
ADD CONSTRAINT FK_A_ANAMEAMENITY
    FOREIGN KEY (ANAMEAMENITY)
    REFERENCES A_AMENITY(ANAME)
ENABLE;
    
ALTER TABLE A_OFFERS
ADD CONSTRAINT FK_A_ROOMTYPE
    FOREIGN KEY (IDROOMTYPE)
    REFERENCES A_ROOMTYPE(ID)
ENABLE;


-- Creaación de la tabla ROOM y especificación de sus restricciones
CREATE TABLE A_ROOM
   (ID NUMBER, 
    IDHOTEL NUMBER,
    IDROOMTYPE NUMBER,
	"NUMBER" VARCHAR2(20 BYTE), 
	"SIZE" VARCHAR2(20 BYTE), 
	CONSTRAINT A_ROOM_PK PRIMARY KEY (ID));
	
ALTER TABLE A_ROOM
ADD CONSTRAINT FK_R_HOTEL
    FOREIGN KEY (IDHOTEL)
    REFERENCES A_HOTEL(id)
ENABLE;

ALTER TABLE A_ROOM
ADD CONSTRAINT FK_R_ROOMTYPE
    FOREIGN KEY (IDROOMTYPE)
    REFERENCES A_ROOMTYPE(id)
ENABLE;

-- Creaación de la tabla BOOKING y especificación de sus restricciones
CREATE TABLE A_BOOKING  
   (ID NUMBER, 
    IDROOM NUMBER,
    NUMBEROFADULTS NUMBER,
    NUMBEROFCHILDREN NUMBER,
    "TYPE" VARCHAR2(20 BYTE),
    BASEPRICE NUMBER,
    MINREQUIREDNIGHTS NUMBER,
    ACCOMODATIONPRICE NUMBER,
    ACCOMMODATIONDISCOUNT NUMBER,
	PAYMENTPLAN VARCHAR2(20 BYTE),
    TOTALVALUE NUMBER,
    PAIDDATE DATE,
    PAID NUMBER(1,0),
	CONSTRAINT A_BOOKING_PK PRIMARY KEY (ID));
	
ALTER TABLE A_BOOKING 
ADD CONSTRAINT FK_A_ROOM
    FOREIGN KEY (IDROOM)
    REFERENCES A_ROOM(id)
ENABLE;

ALTER TABLE A_BOOKING
ADD CONSTRAINT CK_B_TYPE 
	CHECK (TYPE IN ('LONGSTAY', 'TIMESHARE', 'ALLINCLUSIVE', 'PROMOTION'))
ENABLE;


-- Creaación de la tabla OCCUPANCYDATE y especificación de sus restricciones
CREATE TABLE A_OCCUPANCYDATE
   (ID NUMBER, 
    IDROOM NUMBER,
	DATESTART DATE,
    DATEFINISH DATE,
	CONSTRAINT A_OCCUPANCYDATE_PK PRIMARY KEY (ID));
	 

-- Creaación de la tabla OCCUPIEDDATE y especificación de sus restricciones
CREATE TABLE A_OCCUPIEDDATE 
   (IDOCCUPANCYDATE NUMBER, 
	IDROOM NUMBER,
	CONSTRAINT A_OCCUPIEDDATE_PK PRIMARY KEY (IDOCCUPANCYDATE, IDROOM));

ALTER TABLE A_OCCUPIEDDATE
ADD CONSTRAINT FK_AV_IDOCCUPANCYDATE
    FOREIGN KEY (IDOCCUPANCYDATE)
    REFERENCES A_OCCUPANCYDATE(ID)
ENABLE;
    
ALTER TABLE A_OCCUPIEDDATE
ADD CONSTRAINT FK_AV_ROOM
    FOREIGN KEY (IDROOM)
    REFERENCES A_ROOM(ID)
ENABLE;

-- Creaación de la tabla USER y especificación de sus restricciones
CREATE TABLE A_USER
   ("DOCUMENT" NUMBER,
    "PASSWORD" VARCHAR2(255 BYTE),
	DOCUMENTTYPE VARCHAR2(255 BYTE), 
    "NAME" VARCHAR2(255 BYTE),
    EMAIL VARCHAR2(255 BYTE),
    BORNDATE DATE,
    "ROLE" VARCHAR2(20 BYTE), 
	CONSTRAINT A_USER_PK PRIMARY KEY ("DOCUMENT"));

ALTER TABLE A_USER
ADD CONSTRAINT CK_U_ROLE
	CHECK ("ROLE" IN ('CLIENT', 'RECEPTIONIST', 'EMPLOYEE', 'DATAADMIN', 'HOTELMANAGER'))
ENABLE;


-- Creaación de la tabla CHECKINOUT y especificación de sus restricciones
CREATE TABLE A_CHECKINOUT
(
    IDBOOKING NUMBER,
    DOCUMENTUSER NUMBER,
    CHECKINDATE TIMESTAMP,
    CHECKINMADE NUMBER(1,0),
    CHECKOUTDATE TIMESTAMP,
    CHECKOUTMADE NUMBER(1,0),
    CONSTRAINT A_CHECKINOUT_PK PRIMARY KEY (IDBOOKING, DOCUMENTUSER));

ALTER TABLE A_CHECKINOUT
ADD CONSTRAINT FK_C_BOOKING
    FOREIGN KEY (IDBOOKING)
    REFERENCES A_BOOKING(ID)
ENABLE;
    
ALTER TABLE A_CHECKINOUT
ADD CONSTRAINT FK_C_USER
    FOREIGN KEY (DOCUMENTUSER)
    REFERENCES A_USER("DOCUMENT")
ENABLE;

-- Creaación de la tabla SERVICE y especificación de sus restricciones
CREATE TABLE A_SERVICE
   (ID NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
    "DESCRIPTION" VARCHAR2(500 BYTE),
    STARTWORKHOUR NUMBER,
    ENDWORKHOUR NUMBER,
    "TYPE" VARCHAR2(255 BYTE),
    "CATEGORY" VARCHAR2(255 BYTE),
    AVAILABLE NUMBER(1,0),
    AVAILABLECAPACITY NUMBER,
    EMPLOYEETHATREGISTER NUMBER,
	CONSTRAINT A_SERVICE_PK PRIMARY KEY (ID));

ALTER TABLE A_SERVICE
ADD CONSTRAINT FK_R_USER
    FOREIGN KEY (EMPLOYEETHATREGISTER)
    REFERENCES A_USER("DOCUMENT")
ENABLE;

ALTER TABLE A_SERVICE
ADD CONSTRAINT CK_S_TYPE
	CHECK ("TYPE" IN ('POOL', 'GYM', 'INTERNET', 'SUPERMARKET', 'STORE','LAUNDRY', 'UTENSILSLOAN', 'SPA', 'MEETING ROOM', 'CONFERENCE'))
ENABLE;

ALTER TABLE A_SERVICE
ADD CONSTRAINT CK_S_CATEGORY
	CHECK ("CATEGORY" IN ('RESERVABLE', 'GASTRONOMY', 'CONVENIENCE'))
ENABLE;

-- Creaación de la tabla RESERVATION y especificación de sus restricciones
CREATE TABLE A_RESERVATION
   (ID NUMBER, 
    IDSERVICE NUMBER,
    DOCUMENTUSER NUMBER, 
	NUMBEROFGUESTS NUMBER,
    "DURATION" NUMBER,
    "DATE" TIMESTAMP,
	CONSTRAINT A_RESERVATION_PK PRIMARY KEY (ID));

ALTER TABLE A_RESERVATION
ADD CONSTRAINT FK_RE_USER
    FOREIGN KEY (DOCUMENTUSER)
    REFERENCES A_USER("DOCUMENT")
ENABLE;

ALTER TABLE A_RESERVATION
ADD CONSTRAINT FK_RE_SERVICE
    FOREIGN KEY (IDSERVICE)
    REFERENCES A_SERVICE(ID)
ENABLE;

-- Creaación de la tabla CONSUMEDSERVICES y especificación de sus restricciones
CREATE TABLE A_CONSUMEDSERVICES
(
    IDBOOKING NUMBER,
    IDSERVICEINVOICE NUMBER,
    DISCOUNT NUMBER,
    ALLINCLUSIVE NUMBER(1,0),
    CONSTRAINT A_INCLUDEDSERVICES_PK PRIMARY KEY (IDBOOKING, IDSERVICEINVOICE));

ALTER TABLE A_CONSUMEDSERVICES
ADD CONSTRAINT FK_I_BOOKING
    FOREIGN KEY (IDBOOKING)
    REFERENCES A_BOOKING(ID)
ENABLE;
    
ALTER TABLE A_CONSUMEDSERVICES
ADD CONSTRAINT FK_I_SERVICEINVOICE
    FOREIGN KEY (IDSERVICEINVOICE)
    REFERENCES A_SERVICEINVOICE(ID)
ENABLE;

-- Creaación de la tabla SERVICEINVOICE y especificación de sus restricciones
CREATE TABLE A_SERVICEINVOICE
   (ID NUMBER, 
    IDSERVICE NUMBER,
	"VALUE" NUMBER,     
    CREATEDDATE DATE,
    PAIDDATE DATE, 
	CONSTRAINT A_SERVICEINVOICE_PK PRIMARY KEY (ID));

ALTER TABLE A_SERVICEINVOICE
ADD CONSTRAINT FK_S_SERVICE
    FOREIGN KEY (IDSERVICE)
    REFERENCES A_SERVICE(ID)
ENABLE;

-- Creaación de la tabla RESTAURANT y especificación de sus restricciones
CREATE TABLE A_RESTAURANT
   (ID NUMBER, 
    "NAME" VARCHAR2(255 BYTE),
    "TYPE" VARCHAR2(255 BYTE),
    FOODTYPE VARCHAR2(255 BYTE),
    MUSICTYPE VARCHAR2(255 BYTE), 
	CONSTRAINT A_RESTAURANT_PK PRIMARY KEY (ID));

ALTER TABLE A_RESTAURANT
ADD CONSTRAINT CK_R_TYPE
	CHECK ("TYPE" IN ('BAR', 'RESTAURANT'))
ENABLE;

-- Creaación de la tabla FOODPRODUCT y especificación de sus restricciones
CREATE TABLE A_FOODPRODUCT
   (ID NUMBER, 
    IDRESTAURANT NUMBER,
   	"NAME" VARCHAR2(255 BYTE), 
    "DESCRIPTION" VARCHAR2(500 BYTE),
	PRICE NUMBER,     
    IMGSRC VARCHAR2(500 BYTE),
	CONSTRAINT A_FOODPRODUCT_PK PRIMARY KEY (ID));

ALTER TABLE A_FOODPRODUCT
ADD CONSTRAINT FK_F_RESTAURANT
    FOREIGN KEY (IDRESTAURANT)
    REFERENCES A_RESTAURANT(ID)
ENABLE;

-- Creaación de la tabla INCLUDEDFOOD y especificación de sus restricciones
CREATE TABLE A_INCLUDEDFOOD
   (IDBOOKING NUMBER, 
	IDFOODPRODUCT NUMBER,
    MAXNUMBEROFINCLUDEDITEMS NUMBER,
    PRODUCTDISCOUNT NUMBER,
	CONSTRAINT A_INCLUDEDFOOD_PK PRIMARY KEY 
    (IDBOOKING, IDFOODPRODUCT, MAXNUMBEROFINCLUDEDITEMS, PRODUCTDISCOUNT));

ALTER TABLE A_INCLUDEDFOOD
ADD CONSTRAINT FK_IN_BOOKING
    FOREIGN KEY (IDBOOKING)
    REFERENCES A_BOOKING(ID)
ENABLE;
    
ALTER TABLE A_INCLUDEDFOOD
ADD CONSTRAINT FK_IN_FOODPRODUCT
    FOREIGN KEY (IDFOODPRODUCT)
    REFERENCES A_FOODPRODUCT(ID)
ENABLE;

COMMIT;
